-- noinspection SqlNoDataSourceInspectionForFile
INSERT INTO users (date_of_birth, created_on, password, email, address, zip_code, city, country) VALUES ('2000-11-11', '2000-11-11', '111', 'dragan.susak@gmail.com', 'Adresa', '78000', 'BL', 'BA');
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('CHF', 'EUR',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('USD', 'AUD',1.5, '2000-11-11', 1);
insert into conversions (source_currency, target_currency, rate, valid_on, user_id) values ('BAM', 'USD',1.5, '2000-11-11', 1);